### ISSUE TITLE
Watchers wrong, how to get real?

### ISSUE THREAD

**Issue by enough1987** [milo/github-api#26] opened 2019-03-09 16:28 UTC
https://api.github.com/search/repositories?q=vscode
stargazers_count: 70274,
forks_count: 9362,
forks: 9362
watchers_count: 70274, <--(LISTED)
watchers: 70274,

https://github.com/Microsoft/vscode
Stars 70,274
Forks 9,362
Watchers 2,667 <--- (REAL)

**Comment by milo** [comment] 2019-03-15 11:47
Duplicate of #19.

IMHO you should open issue on Github, to be `subscribers_count` item added to search result.

**Closed by milo** 2019-03-15 11:47 UTC
